#pragma once

// AUTO-GENERATED by scripts/compute_lqr_gain.py
// DO NOT EDIT MANUALLY
// 此文件由 Python 脚本自动生成，请勿手动修改

namespace pendulum {

enum class LqrMode {
    kFull,        ///< 均衡模式：速度收敛 + 摆动抑制
    kShortest,    ///< 最短距离模式：优先速度收敛
    kMinSwing     ///< 最小摆动模式：优先摆动抑制
};

struct LqrGain {
    // Full: Q=[2,30,10], R=2
    static constexpr double kFullV     = 0.49511623;
    static constexpr double kFullTheta = -3.60133076;
    static constexpr double kFullOmega = -7.18935072;

    // Shortest: Q=[8,2,1], R=3
    static constexpr double kShortestV     = 1.60551098;
    static constexpr double kShortestTheta = -1.46437809;
    static constexpr double kShortestOmega = -0.96359954;

    // MinSwing: Q=[1,100,50], R=2
    static constexpr double kMinSwingV     = 0.38155897;
    static constexpr double kMinSwingTheta = -5.40290467;
    static constexpr double kMinSwingOmega = -16.39513344;
};

} // namespace pendulum
