#pragma once

// AUTO-GENERATED by scripts/compute_lqr_gain.py
// DO NOT EDIT MANUALLY

namespace pendulum {

enum class LqrMode {
    kDiagonal,      ///< 对角Q模式：Q为对角矩阵，直接惩罚各状态量
    kCoupled        ///< 非对角Q模式：Q包含耦合项，惩罚系统总能量
};

struct LqrGain {
    // Diagonal: Q=diag([8,1000,500,5]), R=2
    static constexpr double kDiagonalV        = 2.17383431;
    static constexpr double kDiagonalTheta    = -28.57682117;
    static constexpr double kDiagonalOmega    = -20.16512650;
    static constexpr double kDiagonalIntegral = 0.19900226;

    // Coupled: Q penalizes system total energy + integral, R=3
    static constexpr double kCoupledV        = 3.73190169;
    static constexpr double kCoupledTheta    = -38.00400016;
    static constexpr double kCoupledOmega    = -6.56048788;
    static constexpr double kCoupledIntegral = 0.62563527;
};

} // namespace pendulum
