#!/usr/bin/env python3
"""
LQI 增益离线计算脚本

功能：为 1-D 俯仰吊重制动控制设计离散 LQI 控制器（带速度误差积分），
      并自动生成 C++ 头文件 include/controller/lqr_gain.hpp。

控制目标：跟踪速度参考指令，同时抑制吊重摆动。
状态向量：x = [vx_err, theta, theta_dot, int_vx_err]^T
控制输入：u = ax（无人机水平加速度）

使用方法：
    python3 scripts/compute_lqr_gain.py
    python3 scripts/compute_lqr_gain.py --rope-length 10.0 --dt 0.02
"""

import numpy as np
from scipy.linalg import solve_discrete_are, expm
import argparse
import os


def build_state_space(g: float, L: float, pendulum_gain: float = 0.6):
    """
    建立连续时间状态空间模型（完整耦合模型小角度线性化）

    状态 x = [vx_err, theta, theta_dot, int_vx_err]^T
    输入 u = ax（名义加速度）

    完整耦合模型（从拉格朗日方程推导）：
        ddx = (a1 + mu*g*sin(theta)*cos(theta) + mu*L*omega^2*sin(theta)) / (1 - mu*cos^2(theta))
        ddtheta = -(ddx*cos(theta) + g*sin(theta)) / L

    在 theta=0, omega=0 附近线性化：
        vx_dot    = a1/(1-mu) + mu*g/(1-mu) * theta
        theta_dot = omega
        omega_dot = -g/(L*(1-mu)) * theta - 1/(L*(1-mu)) * a1
        int_dot   = vx_err

    其中 mu = pendulum_gain = m/(M+m)
    """
    mu = pendulum_gain
    denom = 1.0 - mu

    A = np.array([
        [0.0, mu * g / denom, 0.0, 0.0],     # vx_dot = a1/(1-mu) + mu*g/(1-mu)*theta
        [0.0, 0.0, 1.0, 0.0],                 # theta_dot = omega
        [0.0, -g / (L * denom), 0.0, 0.0],   # omega_dot = -g/(L*(1-mu))*theta - ...
        [1.0, 0.0, 0.0, 0.0]                  # int_dot = vx_err
    ], dtype=float)

    B = np.array([
        [1.0 / denom],           # 加速度直接影响速度 (放大 1/(1-mu))
        [0.0],                   # 加速度不直接影响角度
        [-1.0 / (L * denom)],    # 加速度通过惯性力影响角加速度
        [0.0]                    # 加速度不直接影响积分
    ], dtype=float)

    return A, B


def c2d(A, B, dt):
    """
    零阶保持（ZOH）离散化
    """
    n = A.shape[0]
    m = B.shape[1]
    M = np.block([
        [A, B],
        [np.zeros((m, n)), np.zeros((m, m))]
    ])
    M_exp = expm(M * dt)
    Ad = M_exp[:n, :n]
    Bd = M_exp[:n, n:]
    return Ad, Bd


def solve_lqr(Ad, Bd, Q, R_val):
    """
    求解离散 LQR 的最优反馈增益 K
    """
    if isinstance(Q, (list, tuple)):
        Q = np.diag(Q)
    R = np.array([[R_val]])
    P = solve_discrete_are(Ad, Bd, Q, R)
    K = np.linalg.solve(R + Bd.T @ P @ Bd, Bd.T @ P @ Ad).flatten()
    return K


def generate_lqr_gains(
    rope_length: float = 15.0,
    gravity: float = 9.81,
    dt_control: float = 0.02,
    pendulum_gain: float = 0.6,
    output_path: str = None,
):
    """
    生成两种 LQI 控制模式的增益

    两种模式：
    1. Diagonal（对角Q模式）: Q = diag([qv, q_theta, q_omega, q_int]), R = r
    2. Coupled（非对角Q模式）: Q 包含耦合项 + 积分权重, R = r
    """
    A, B = build_state_space(gravity, rope_length, pendulum_gain)
    Ad, Bd = c2d(A, B, dt_control)

    # Mode 1: Diagonal - 对角Q，直接惩罚状态量 + 积分
    # 增大 q_omega 确保 K_omega < 0（提供正阻尼）
    K_diagonal = solve_lqr(Ad, Bd, [8.0, 1000.0, 3000.0, 0.1], 2.0)

    # Mode 2: Coupled - 非对角Q，惩罚系统总能量 + 积分
    # q_ke=0 去掉速度-角速度耦合，使 K_omega 更容易为负
    q_drone = 20.0
    q_pe_sys = 3000.0
    q_omega_extra_sys = 2000.0
    q_int = 1.0
    Q_coupled = np.array([
        [q_drone, 0.0, 0.0, 0.0],
        [0.0, q_pe_sys, 0.0, 0.0],
        [0.0, 0.0, q_omega_extra_sys, 0.0],
        [0.0, 0.0, 0.0, q_int]
    ], dtype=float)
    K_coupled = solve_lqr(Ad, Bd, Q_coupled, 2.0)

    # 打印闭环极点，验证稳定性
    print("=" * 60)
    print(f"LQI 增益设计结果（速度跟踪 + 摆动抑制 + 积分消除稳态误差）")
    print(f"绳长 L = {rope_length:.3f} m, 控制周期 Ts = {dt_control:.3f} s")
    print("=" * 60)

    for name, K in [("Diagonal", K_diagonal), ("Coupled", K_coupled)]:
        Acl = Ad - Bd @ K.reshape(1, -1)
        eigs = np.linalg.eigvals(Acl)
        max_eig = max(abs(eigs))

        print(f"\n{name}:")
        print(f"  增益 K = [{K[0]:.6f}, {K[1]:.6f}, {K[2]:.6f}, {K[3]:.6f}]")
        print(f"  闭环最大特征值 = {max_eig:.4f}", end="")
        if max_eig < 1.0:
            print("  ✓ 稳定")
        else:
            print("  ⚠ 不稳定")

    print("=" * 60)

    if output_path is None:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_path = os.path.join(script_dir, "..", "..", "include", "controller", "lqr_gain.hpp")
        output_path = os.path.abspath(output_path)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    header_content = f"""#pragma once

// AUTO-GENERATED by scripts/compute_lqr_gain.py
// DO NOT EDIT MANUALLY

namespace pendulum {{

enum class LqrMode {{
    kDiagonal,      ///< 对角Q模式：Q为对角矩阵，直接惩罚各状态量
    kCoupled        ///< 非对角Q模式：Q包含耦合项，惩罚系统总能量
}};

struct LqrGain {{
    // Diagonal: Q=diag([8,1000,500,5]), R=2
    static constexpr double kDiagonalV        = {K_diagonal[0]:.8f};
    static constexpr double kDiagonalTheta    = {K_diagonal[1]:.8f};
    static constexpr double kDiagonalOmega    = {K_diagonal[2]:.8f};
    static constexpr double kDiagonalIntegral = {K_diagonal[3]:.8f};

    // Coupled: Q penalizes system total energy + integral, R=3
    static constexpr double kCoupledV        = {K_coupled[0]:.8f};
    static constexpr double kCoupledTheta    = {K_coupled[1]:.8f};
    static constexpr double kCoupledOmega    = {K_coupled[2]:.8f};
    static constexpr double kCoupledIntegral = {K_coupled[3]:.8f};
}};

}} // namespace pendulum
"""

    with open(output_path, "w") as f:
        f.write(header_content)

    print(f"\n已生成: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="计算 LQI 增益")
    parser.add_argument("--rope-length", type=float, default=15.0, help="绳长 [m]")
    parser.add_argument("--gravity", type=float, default=9.81, help="重力加速度 [m/s^2]")
    parser.add_argument("--dt", type=float, default=0.02, help="控制周期 [s]")
    parser.add_argument("--pendulum-gain", type=float, default=0.6, help="摆动耦合增益 [-]")
    parser.add_argument("--output", type=str, default=None, help="输出文件路径")
    args = parser.parse_args()

    generate_lqr_gains(
        rope_length=args.rope_length,
        gravity=args.gravity,
        dt_control=args.dt,
        pendulum_gain=args.pendulum_gain,
        output_path=args.output,
    )


if __name__ == "__main__":
    main()
