#!/usr/bin/env python3
"""
Compute LQR gain for the 1-D pitch slung-load system.

Generates include/controller/lqr_gain.hpp with the discrete-time LQR gain.
"""

import numpy as np
from scipy.linalg import solve_continuous_are, solve_discrete_are, expm
import argparse
import os


def build_state_space(g: float, L: float):
    """
    Build continuous-time state-space matrices for:
        x = [px_error, vx, theta, theta_dot]^T
        u = ax

    A = [[0, 1,   0,    0],
         [0, 0,   0,    0],
         [0, 0,   0,    1],
         [0, 0, g/L,    0]]

    B = [[0],
         [1],
         [0],
         [-1/L]]
    """
    A = np.array([
        [0.0, 1.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
        [0.0, 0.0, -g / L, 0.0]
    ], dtype=float)

    B = np.array([
        [0.0],
        [1.0],
        [0.0],
        [-1.0 / L]
    ], dtype=float)

    return A, B


def c2d(A, B, dt):
    """Zero-order-hold discretization."""
    n = A.shape[0]
    m = B.shape[1]
    M = np.block([
        [A, B],
        [np.zeros((m, n)), np.zeros((m, m))]
    ])
    M_exp = expm(M * dt)
    Ad = M_exp[:n, :n]
    Bd = M_exp[:n, n:]
    return Ad, Bd


def generate_lqr_gain(
    rope_length: float = 15.0,
    gravity: float = 9.81,
    dt_control: float = 0.02,
    q_px: float = 1.0,
    q_vx: float = 0.5,
    q_theta: float = 10.0,
    q_omega: float = 1.0,
    r_ax: float = 1.0,
    output_path: str = None,
):
    A, B = build_state_space(gravity, rope_length)
    Ad, Bd = c2d(A, B, dt_control)

    Q = np.diag([q_px, q_vx, q_theta, q_omega])
    R = np.array([[r_ax]])

    # Solve discrete-time algebraic Riccati equation
    P = solve_discrete_are(Ad, Bd, Q, R)

    # Discrete LQR gain: K = (R + B^T P B)^-1 B^T P A
    K = np.linalg.solve(R + Bd.T @ P @ Bd, Bd.T @ P @ Ad).flatten()

    print("=" * 60)
    print(f"LQR Gain Design Parameters")
    print("=" * 60)
    print(f"Rope length L      : {rope_length:.3f} m")
    print(f"Control period Ts  : {dt_control:.3f} s")
    print(f"Natural freq wn    : {np.sqrt(gravity/rope_length):.4f} rad/s")
    print(f"Q = diag({q_px}, {q_vx}, {q_theta}, {q_omega})")
    print(f"R = [{r_ax}]")
    print("-" * 60)
    print(f"Continuous eigenvalues : {np.linalg.eigvals(A)}")
    print(f"Discrete eigenvalues   : {np.linalg.eigvals(Ad)}")
    print("-" * 60)
    print(f"Discrete LQR Gain K = [{K[0]:.6f}, {K[1]:.6f}, {K[2]:.6f}, {K[3]:.6f}]")
    print("=" * 60)

    # Closed-loop eigenvalues
    Acl = Ad - Bd @ K.reshape(1, -1)
    eigs_cl = np.linalg.eigvals(Acl)
    print(f"Closed-loop discrete eigenvalues: {eigs_cl}")
    print(f"Max |eig| = {max(abs(eigs_cl)):.4f}")
    print("=" * 60)

    if output_path is None:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_path = os.path.join(script_dir, "..", "include", "controller", "lqr_gain.hpp")
        output_path = os.path.abspath(output_path)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    header_content = f"""#pragma once

// AUTO-GENERATED by scripts/compute_lqr_gain.py
// DO NOT EDIT MANUALLY

namespace pendulum {{

/**
 * @brief Pre-computed discrete-time LQR gain for 1-D pitch slung-load.
 *
 * Design parameters:
 *   L       = {rope_length:.3f} m
 *   Ts      = {dt_control:.3f} s
 *   Q_diag  = [{q_px}, {q_vx}, {q_theta}, {q_omega}]
 *   R       = [{r_ax}]
 *
 * State vector: [px_error, vx, theta, theta_dot]^T
 * Control law:  u = -K * x
 */
struct LqrGain {{
    static constexpr double kP     = {K[0]:.8f};
    static constexpr double kV     = {K[1]:.8f};
    static constexpr double kTheta = {K[2]:.8f};
    static constexpr double kOmega = {K[3]:.8f};
}};

}} // namespace pendulum
"""

    with open(output_path, "w") as f:
        f.write(header_content)

    print(f"\nGenerated: {output_path}")
    return K


def main():
    parser = argparse.ArgumentParser(description="Compute LQR gain for slung-load system")
    parser.add_argument("--rope-length", type=float, default=15.0, help="Rope length [m]")
    parser.add_argument("--gravity", type=float, default=9.81, help="Gravity [m/s^2]")
    parser.add_argument("--dt", type=float, default=0.02, help="Control period [s]")
    parser.add_argument("--q-px", type=float, default=1.0, help="Position weight")
    parser.add_argument("--q-vx", type=float, default=0.5, help="Velocity weight")
    parser.add_argument("--q-theta", type=float, default=10.0, help="Angle weight")
    parser.add_argument("--q-omega", type=float, default=1.0, help="Angular rate weight")
    parser.add_argument("--r-ax", type=float, default=1.0, help="Control weight")
    parser.add_argument("--output", type=str, default=None, help="Output header file path")
    args = parser.parse_args()

    generate_lqr_gain(
        rope_length=args.rope_length,
        gravity=args.gravity,
        dt_control=args.dt,
        q_px=args.q_px,
        q_vx=args.q_vx,
        q_theta=args.q_theta,
        q_omega=args.q_omega,
        r_ax=args.r_ax,
        output_path=args.output,
    )


if __name__ == "__main__":
    main()
